<?php

namespace ContainerMAEz5tx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0A7H.F.App\Controller\HomeController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z0A7H.F'] ?? $container->load('get_ServiceLocator_Z0A7H_FService'));

        if (isset($container->privates['.service_locator.z0A7H.F.App\\Controller\\HomeController::add()'])) {
            return $container->privates['.service_locator.z0A7H.F.App\\Controller\\HomeController::add()'];
        }

        return $container->privates['.service_locator.z0A7H.F.App\\Controller\\HomeController::add()'] = $a->withContext('App\\Controller\\HomeController::add()', $container);
    }
}
