<?php

namespace ContainerMAEz5tx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIdeaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IdeaController' shared autowired service.
     *
     * @return \App\Controller\IdeaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/IdeaController.php';

        $container->services['App\\Controller\\IdeaController'] = $instance = new \App\Controller\IdeaController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\IdeaController', $container));

        return $instance;
    }
}
