<?php

namespace ContainerJQcoXrG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SDe9A1fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SDe9A1f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SDe9A1f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\HomeController::add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\HomeController::add()', 'getHomeControlleraddService', true],
            'App\\Controller\\LogginController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\LogginController::login()', 'getLogginControllerloginService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\HomeController:add' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\HomeController::add()', 'getHomeControlleraddService', true],
            'App\\Controller\\LogginController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\LogginController::login()', 'getLogginControllerloginService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.vOo7mW7.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\HomeController::add' => '?',
            'App\\Controller\\LogginController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\HomeController:add' => '?',
            'App\\Controller\\LogginController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
        ]);
    }
}
