<?php

namespace ContainerBwPPOSQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XpjzgDOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XpjzgDO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XpjzgDO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\LogginController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\LogginController::login()', 'getLogginControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\LogginController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\LogginController::login()', 'getLogginControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LogginController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LogginController:login' => '?',
        ]);
    }
}
