<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEPHGXCs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEPHGXCs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEPHGXCs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEPHGXCs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEPHGXCs\App_KernelDevDebugContainer([
    'container.build_hash' => 'EPHGXCs',
    'container.build_id' => 'bb362105',
    'container.build_time' => 1771361341,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEPHGXCs');
