<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDWzEgL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDWzEgL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDWzEgL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDWzEgL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTDWzEgL\App_KernelDevDebugContainer([
    'container.build_hash' => 'TDWzEgL',
    'container.build_id' => '443c3e3c',
    'container.build_time' => 1771187404,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDWzEgL');
