<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSVVkGA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSVVkGA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZSVVkGA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZSVVkGA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZSVVkGA\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZSVVkGA',
    'container.build_id' => '31fda32b',
    'container.build_time' => 1771345641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSVVkGA');
